version: '2'

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge

services:
  janus-gateway:
    build: .
    container_name: janus-gateway
    volumes:
      - ./lua.cfg:/opt/janus/etc/janus/janus.plugin.lua.cfg
      - ./myscript.lua:/opt/janus/share/janus/lua/myscript.lua
      - ./janus.log:/var/log/janus.log
    ports:
      - 8088:8088
      - 8188:8188
    networks:
      - back-tier
      - front-tier
